//
// Created by Naum Puroski on 15/10/2016.
//

#ifndef FRIENDLYWITHC_CONCRETECONNECTION_H
#define FRIENDLYWITHC_CONCRETECONNECTION_H


class ConcreteConnection {

};


#endif //FRIENDLYWITHC_CONCRETECONNECTION_H
