#include <iostream>
#include <sstream>
#include "container.h"
#include "MyType.h"
#include "Pimpl.h"

void test_my_type2_size();
void test_my_type2_method();

int main() {
    std::cout << "\nMyType size Tests" << std::endl;
    std::cout << "size of MyType<int> is " << sizeof(MyType<int>) << std::endl;
    std::cout << "sise of Priv<MyType<int> is " << sizeof(Pimpl<MyType<int>>) << std::endl;
    test_my_type2_size();

    std::cout << "\nMyType.h Tests" << std::endl;
    std::cout << "method1 = " << MyType<int>{1, 1}.method1() << std::endl;
    std::cout << "method2 = " << MyType<int>{1, 1}.method2() << std::endl;
    std::cout << "pimpl<type1>.method1 = " << Pimpl<MyType<int>>().method1() << std::endl;
    std::cout << "pimpl<type1>.method2 = " << Pimpl<MyType<int>>().method2() << std::endl;

    std::cout << "\nMyType2.h Tests, both methods generated by MyType access member out of boundary in MyType2" << std::endl;
    test_my_type2_method();

    return 0;
}